# Generated by Django 3.0.8 on 2022-07-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclient',
            name='client_tag',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
