# Generated by Django 3.0.8 on 2022-07-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0003_subcriber_subcription_trainer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcription',
            new_name='Subscription',
        ),
    ]
