# Generated by Django 3.0.8 on 2022-07-13 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0004_auto_20220713_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_validity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subcriber',
        ),
        migrations.DeleteModel(
            name='Subcriber',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifit.Subscription'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
