# Generated by Django 4.0.6 on 2022-08-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0006_auto_20220715_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='highlight_status',
        ),
        migrations.AlterField(
            model_name='customclient',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
