# Generated by Django 4.0.6 on 2022-11-02 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0008_alter_customclient_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('Day(s)', 'Day(s)'), ('Week', 'Week'), ('Month(s)', 'Month(s)')], max_length=100)),
                ('discount_percent', models.IntegerField()),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ifit.subscriptionplan')),
            ],
        ),
    ]
