# Generated by Django 4.0.6 on 2022-12-28 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0010_plandiscount_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paystack_payment_reference',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='reg_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
