# Generated by Django 4.0.6 on 2023-01-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0012_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
