# Generated by Django 4.0.6 on 2023-01-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0015_subscription_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
