# Generated by Django 4.0.6 on 2023-01-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0016_alter_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(choices=[('Basic', 'Basic $250'), ('Medium', 'Medium $350'), ('Advance', 'Advance $500')], null=True),
        ),
    ]
