# Generated by Django 4.0.6 on 2023-01-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0018_alter_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_plan', to='ifit.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_price', to='ifit.subscriptionplan'),
        ),
    ]
