# Generated by Django 4.0.6 on 2023-01-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0021_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandiscount',
            name='period',
        ),
    ]
