# Generated by Django 4.0.6 on 2023-01-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0022_remove_plandiscount_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], null=True, on_delete=django.db.models.deletion.CASCADE, to='ifit.subscriptionplan'),
        ),
    ]
