# Generated by Django 4.0.6 on 2023-01-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifit', '0023_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-plan',)},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ifit.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(),
        ),
    ]
